### ISSUE TITLE
Not working with Nuxt 2

### ISSUE THREAD

**Issue by Tragio** [alvarotrigo/nuxt-fullpage#1]
Hello @alvarotrigo @JonathanSchndr 👋 

I noticed that this is not working with Nuxt 2.

When I start the development I get:

```
WARN  Module @fullpage/nuxt-fullpage is disabled due to incompatibility issues:                                                                                                                       09:00:36
 - [nuxt] Nuxt version `^3.0.0` is required but currently using `2.15.8
```

And in the console:
```
[Vue warn]: Unknown custom element: <full-page> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pages/intro.vue> at pages/intro.vue
       <Nuxt>
         <Layouts/default.vue> at layouts/default.vue
           <Root>
```

Really thank you! 🙂

**Comment by JonathanSchndr** [comment]
Hey @Tragio 👋,

yes, that is correct! The plugin only works with Vue 3 and therefore Nuxt 3.
Vue 2 and Nuxt 2 is no longer supported. 

We should maybe make this clearer in the README.
Thanks for your feedback!

**Comment by Tragio** [comment]
Hi @JonathanSchndr 👋 

That would be awesome. So for Nuxt 2, what should be the correct way to use with FullPage v4? If this is not possible, how can I downgrade my license for FullPage v3?

**Comment by JonathanSchndr** [comment]
@Tragio For license questions please submit your request directly to https://alvarotrigo.com/contact/.

Maybe it makes sense to set up a depreacted version in an extra branch for Vue 2 and Nuxt 2 @alvarotrigo?

**Comment by alvarotrigo** [comment]
> Maybe it makes sense to set up a deprecated version in an extra branch for Vue 2 and Nuxt 2 @alvarotrigo?

Yeah, that sounds good to me.
Easy to install using npm and easy to access too.

**Comment by alvarotrigo** [comment]
> So for Nuxt 2, what should be the correct way to use with FullPage v4? If this is not possible, how can I downgrade my license for FullPage v3?

Sure, happy to help you out through the [contact form](https://alvarotrigo.com/contact/)..

**Comment by Tragio** [comment]
@alvarotrigo thank you 😊 @JonathanSchndr do you have any ETA for FullPage v4 for Vue 2? If so, I can then use it instead of downgrading.

**Comment by alvarotrigo** [comment]
> do you have any ETA for FullPage v4 for Vue 2? If so, I can then use it instead of downgrading.

Unfortunately, that's not gonna happen.
Integrations with Vue 2 won't be maintained anymore.
