### ISSUE TITLE
How to use it in NXUT？

### ISSUE THREAD

**Issue by lintiansheng** [alvarotrigo/nuxt-fullpage#10]
The installation steps are introduced and then put in the sample code and will not run
![image](https://github.com/alvarotrigo/nuxt-fullpage/assets/28556994/4bd85d81-7602-49e8-8693-c386ed6afeba)
 <div>
            <p>测试</p>
            <full-page ref="fullpage" :options="options" id="fullpage">
            <div class="section">First section ...</div>
            <div class="section">Second section ...</div>
        </full-page>
        </div>
        
            data:()=>({
        options: {
            menu: '#menu',
            anchors: ['page1', 'page2', 'page3'],
            sectionsColor: ['#41b883', '#ff5f45', '#0798ec'],
        }
        }）

**Comment by alvarotrigo** [comment]
Did you check the example?
That should be working.
https://github.com/alvarotrigo/nuxt-fullpage/tree/main/playground

Use `npm run dev:build` and `npm run dev` to run it.

See what's the difference with your code.
