### ISSUE TITLE
How to use it in nuxt2x, not nuxt3x

### ISSUE THREAD

**Issue by lintiansheng** [alvarotrigo/nuxt-fullpage#12]
It's a pity that the official website example is Nuxt3，Hope to get your guidance

**Comment by alvarotrigo** [comment]
We don't provide support for Nuxt2 anymore.
Perhaps you can take a look at older versions of fullPage.js to get some guidance:
https://github.com/alvarotrigo/vue-fullpage.js/tree/0.1.5#usage-with-nuxtjs
