### ISSUE TITLE
Cannot read properties of null (reading 'item')

### ISSUE THREAD

**Issue by jacksonthatsme** [alvarotrigo/nuxt-fullpage#13]
Im seeing an error that is breaking the function of the module when I include it in my project. I just got a lifetime license to make sure it wasn't the issue. I followed all the install instructions to the letter, and I included this module in a project last year with very little friction and checked my implementation from that very similar stack and I'm not seeing any glaring discrepancies that would suggest this error. Any guidance would be greatly appreciated!

Here's my package.json, Im using Nuxt 3.9.3 and Vue 3.4.14
<img width="484" alt="Screenshot 2024-01-31 at 1 15 42 AM" src="https://github.com/alvarotrigo/nuxt-fullpage/assets/3342512/a0673f17-f593-40ac-8bc4-aba15cb8997a">

I included it as documented in the nuxt.config 
<img width="548" alt="Screenshot 2024-01-31 at 1 15 15 AM" src="https://github.com/alvarotrigo/nuxt-fullpage/assets/3342512/62c5f44c-af88-4769-bd27-43ddec3f9b3f">

And then I'm including it in my index.vue, using the same options from my previous project, and wrapping in a ClientOnly tag, which worked just fine previously,
<img width="672" alt="Screenshot 2024-01-31 at 1 14 54 AM" src="https://github.com/alvarotrigo/nuxt-fullpage/assets/3342512/55f3612e-8e96-42ac-827b-8ef11d3a1aac">

But im getting these breaking errors that I'm uncertain how to troubleshoot further.
![301058450-af71ab4f-bba9-44f5-8135-14b3ad239e24](https://github.com/alvarotrigo/nuxt-fullpage/assets/3342512/1f831b37-393b-4235-bec2-72106e28802b)

Hoping someone can help! And maybe others can learn from my issue *fingers crosses* Thanks!

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction in codesandbox so we can investigate further?
Then let us know the steps to reproduce it and the device & browser you are using.

**Comment by jacksonthatsme** [comment]
Hi! Thanks for getting back to me. Trying to get together the resources you requested to help debug. I ported my repo to this codesandbox and Im seeing the same error as before. Here is the [link](https://codesandbox.io/p/github/jacksonthatsme/illuminyti/main?file=%2Fpages%2Findex.vue%3A19%2C3&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsgigb0d00063b6huacx83hh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsgigb0c00023b6hzvl55u3q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsgigb0c00043b6hyz0gz2fi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsgigb0c00053b6hafpujtn4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsgigb0c00023b6hzvl55u3q%2522%253A%257B%2522id%2522%253A%2522clsgigb0c00023b6hzvl55u3q%2522%252C%2522activeTabId%2522%253A%2522clsgitg1200023b6isxanrzg1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsgigb0c00013b6hmlldi62k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsgitg1200023b6isxanrzg1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A3%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clsgjd3ca005w3b6hhsv6v459%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clsgigb0c00053b6hafpujtn4%2522%253A%257B%2522id%2522%253A%2522clsgigb0c00053b6hafpujtn4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsgiko3000j73b6h0zw50lux%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsgiko3000j73b6h0zw50lux%2522%257D%252C%2522clsgigb0c00043b6hyz0gz2fi%2522%253A%257B%2522id%2522%253A%2522clsgigb0c00043b6hyz0gz2fi%2522%252C%2522activeTabId%2522%253A%2522clsgomkds01ie3b6imnfvc207%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsgobsas010g3b6i5jau3hz8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsgobsdo000cdahx0p078q8t%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsgomkds01ie3b6imnfvc207%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). I'm on a Macbook Pro M1, using Chrome V121.0.6167.139 and I also tested on Safari V16.1 and received the same error. Steps to reproduce: I have two full screen containers, and when I swipe up or down on either, I get the error in the screenshot in the initial post, signaling that the library script is unable to operate on a null. Please let me know what else I need to supply in order to troubleshoot this issue.

**Comment by mulhoon** [comment]
@jacksonthatsme I had the same error, which took me hours to debug. But it seems as though it's quite simple - The slides need a class called `section`
e.g.
```html
<full-page ref="fullpage" :options="options" id="fullpage">
   <transciever class="section"></transciever>
   <missions class="section"></missions>
</full-page>

```

**Comment by alvarotrigo** [comment]
Oh yeah, all sections and slides required the class `section` or `slide` as pointed out in the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a>

Remember this is just a wrapper around the main library, so consulting the main docs is always a must ;) 

Thanks for clarifying it for him @mulhoon !
