### ISSUE TITLE
nuxt-fullpage is not working with Nuxt3 SSR

### ISSUE THREAD

**Issue by 0xhardman** [alvarotrigo/nuxt-fullpage#2]
Hi! I think this doesn't work in Nuxt3 SSR,
When I start the playground in dev mode and set the browser to not allow websites to use Javascript,
Nothing happens to my site, all of it is a white page,
How to use Nuxt3 SSR with full page?

**Comment by JonathanSchndr** [comment]
> 

Currently we do not have SSR support. However, you are welcome to create a sandbox where we can take a closer look at your problem. Thank you!

**Comment by 0xhardman** [comment]
[codepenlink](https://codesandbox.io/s/rchip6?file=/app.vue), sorry, but I got new problem, why it warns 
```
[Vue warn]: Failed to resolve component: full-page
```

**Comment by JonathanSchndr** [comment]
> [codepenlink](https://codesandbox.io/s/rchip6?file=/app.vue), sorry, but I got new problem, why it warns
> 
> ```
> [Vue warn]: Failed to resolve component: full-page
> ```

Your errors are a problem of Codesandbox. Download the project once with File > Export as ZIP and run it locally. It will work directly. If you want to deactivate the SSR, then include <full-page> with <client-only>. The [Vue warn]: Failed to resolve component: full-page is currently a Nuxt 3 Bug.
