### ISSUE TITLE
Character '@' made section render failed

### ISSUE THREAD

**Issue by 0xhardman** [alvarotrigo/nuxt-fullpage#4]
My code is like this
```js
<full-page id="fullpage" ref="fullpage" :options="options">
      <div class="section">
        <h3>Section 1</h3>
      </div>
      <div class="section">
        <h3>abd@efg</h3>
      </div>
 </full-page>
```
I found if there is a '@' character, the section won't be render in production(npm run build).
Maybe it is a bug? Or how can I fix it?

**Comment by JonathanSchndr** [comment]
> My code is like this
> 
> ```js
> 
> <full-page id="fullpage" ref="fullpage" :options="options">
> 
>       <div class="section">
> 
>         <h3>Section 1</h3>
> 
>       </div>
> 
>       <div class="section">
> 
>         <h3>abd@efg</h3>
> 
>       </div>
> 
>  </full-page>
> 
> ```
> 
> I found if there is a '@' character, the section won't be render in production(npm run build).
> 
> Maybe it is a bug? Or how can I fix it?

Can you creating a sandbox so that we can recreate your error? Thank you!
