### ISSUE TITLE
Vue Hydrate Problem - Nuxt

### ISSUE THREAD

**Issue by vinimarcili** [alvarotrigo/nuxt-fullpage#6]
In console, nuxt give me this Warn:

```
runtime-core.esm-bundler.js:40 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM: <!---->  
  at <FullPage id="fullpage" ref="fullpage" options= {licenseKey: '***', menu: '#menu', responsiveWidth: 991, afterLoad: ƒ, onLeave: ƒ}  ... > 
  at <[mediakit] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/vinimarcili" routeProps= {Component: {…}, route: {…}} pageKey="/vinimarcili"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <FragmentWrapper > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <App key=2 > 
  at <NuxtRoot>
  ```
  
But, here's the problem:
When I view the page source, all the HTML insite full-page is missing.
That is, I may have an indexing problem since the SSR is not bringing this content.
But the content that is outside the fullPage returns.

Also, I've tried use the `:skip-init` option, but the HTML still missing in source-code.

Environment

 - node: v16.14.2
 - nuxt: 3.1.0
 - @fullpage/nuxt-fullpage: 0.2.3

**Comment by JonathanSchndr** [comment]
Hey @vinimarcili 
Thank you for your request. Can you please create a code sandbox where we can reproduce the problem? Thank you!

**Comment by JonathanSchndr** [comment]
Fixed in release https://github.com/alvarotrigo/nuxt-fullpage/releases/tag/0.2.5
